run:
  name: "dynamic_eval"
  seed: 42
  gpu_ids: "1"
  save_dir: "./save"
  notes: "xxx."

data:
  data_folder: "/Your/Data/Path/"
  file_list_path: "/Your/Dataset/Label_CSV/FileList.csv"
  data_loader_type: "standard"
  batch_size: 16
  num_workers: 8
  frames: 32
  img_size: 112
  frequency: 4
  p_interval_train: [0.9, 1.0]
  p_interval_test: [0.95]
  aug: False
  use_tabular_data: False
  tabular_cols: [ 'ESV', 'EDV' ]
  tabular_config:
    dim: 2
    hidden_dim: 64

model:
  feature_extractor:
    name: "uniformer_small"

  regressor_head:
    name: "diffusion"
    diffusion:
      n_diffusion_steps: 1000
      time_emb_dim: 64
      predictor_config:
        name: "LegacyAttention"  # Or "MLP", or "LegacyAttention (MCSN)"
        params:
          hidden_dim: 256
          n_head: 8
#          depth: 4

evaluation:
  val_n_clips_per_sample: 1
  inference_samples: 40

  sampler: "ddim"
  ddim_steps: 10
  ddim_eta: 0.0

wandb:
  use: True
  use_for_evaluation: True
  project: "EVAL_Dynamic"
